// (c) 2018 Simul.co

#include "/Engine/Public/Platform.ush"

Texture2D InTexture;
SamplerState InSampler;

void MainVS(
	float2 InPosition : ATTRIBUTE0,
	float2 InUV       : ATTRIBUTE1,
	out float2 OutUV  : TEXCOORD0,
	out float4 OutPosition : SV_POSITION
	)
{
	OutUV       = InUV;
	OutPosition = float4(InPosition, 0.0, 1.0);
}

float4 MainPS(float2 InUV : TEXCOORD0) : SV_TARGET0
{
	return InTexture.SampleLevel(InSampler, InUV, 0);
}
