// (c) 2019 Simul.co

#include "/Engine/Public/Platform.ush"
#include "/Plugin/RemotePlay/Private/Common.ush"

RWTexture2D<float4> RWOutputTexture;

[numthreads(16, 16, 1)]
void MainCS(uint2 ThreadID : SV_DispatchThreadID)
{
	RWOutputTexture[int2(ThreadID.x, ThreadID.y)] = float4(0.5,0.0,1.0,1.0);
}

uint MipIndex;
uint NumMips;

void UpdateReflectionsPS(
	FScreenVertexOutput Input,
	out float4 OutColor : SV_Target0
)
{
	OutColor = float4(0.5,0.0,1.0,1.0);
}
