name: Build PC Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    env:
      WORKFLOW_BUILD_TYPE: Release
      WORKFLOW_VULKAN_DIR: D:/a/Teleport/Teleport/VULKAN_SDK
      Path: $Path;$WORKFLOW_VULKAN_DIR/Bin

    steps:
    - name: Vulkan
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.290.0
    - name: Initial Checks
      run: cmake --version;
        echo $VULKAN_SDK_DIR;
        echo $VULKAN_SDK;
        dir ${{env.WORKFLOW_VULKAN_DIR}}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: 'true'
        submodules: 'false'
    - name: Git Submodules
      run: |
        cd ${{github.workspace}}
        git submodule update --init --recursive --force -- "firstparty/Platform" "thirdparty/draco" "thirdparty/basis_universal" "thirdparty/libdatachannel" "libavstream/thirdparty/curl" "libavstream/thirdparty/efp" "thirdparty/websocketpp" "thirdparty/flecs"
        cd ${{github.workspace}}/thirdparty/libdatachannel
        #git submodule update --init --recursive --force -- "deps/libsrtp"
        #dir deps
        #cd ${{github.workspace}}/thirdparty/libdatachannel
    - name: Running cmake (windows)
      run: |
        cd ${{ github.workspace }}
        mkdir build_pc_client
        cd build_pc_client
        cmake -S .. -B . -WNo-dev -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DTELEPORT_SOLUTION_NAME=TeleportClient -DVULKAN_SDK_DIR=${{env.WORKFLOW_VULKAN_DIR}} -DVulkan_LIBRARY=${{env.WORKFLOW_VULKAN_DIR}}/Lib/vulkan-1.lib -DVulkan_INCLUDE_DIR=${{env.WORKFLOW_VULKAN_DIR}}/Include -DVulkan_GLSLANG_VALIDATOR_EXECUTABLE=${{env.WORKFLOW_VULKAN_DIR}}/Bin/glslangvalidator.exe -DVulkan_GLSLC_EXECUTABLE=${{env.WORKFLOW_VULKAN_DIR}}/Bin/glslc.exe -DCMAKE_BUILD_TYPE=Release -DENABLE_ENCRYPTION=false -DPLATFORM_SUPPORT_OPENGL=false -DPLATFORM_SUPPORT_VULKAN=true -DPLATFORM_SUPPORT_D3D11=false -DPLATFORM_SUPPORT_D3D12=false -DSIMUL_BUILD_SAMPLES=false -DPLATFORM_BUILD_SAMPLES=false -DPLATFORM_BUILD_MD_LIBS=false -DTELEPORT_CLIENT_USE_D3D12=false -DTELEPORT_CLIENT_USE_VULKAN=true
        # once more, now we can get a solution name.
        cmake -S .. -B . -WNo-dev -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DTELEPORT_SOLUTION_NAME=TeleportClient -DVULKAN_SDK_DIR=${{env.WORKFLOW_VULKAN_DIR}} -DVulkan_LIBRARY=${{env.WORKFLOW_VULKAN_DIR}}/Lib/vulkan-1.lib -DVulkan_INCLUDE_DIR=${{env.WORKFLOW_VULKAN_DIR}}/Include -DVulkan_GLSLANG_VALIDATOR_EXECUTABLE=${{env.WORKFLOW_VULKAN_DIR}}/Bin/glslangvalidator.exe -DVulkan_GLSLC_EXECUTABLE=${{env.WORKFLOW_VULKAN_DIR}}/Bin/glslc.exe -DCMAKE_BUILD_TYPE=Release -DENABLE_ENCRYPTION=false -DPLATFORM_SUPPORT_OPENGL=false -DPLATFORM_SUPPORT_VULKAN=true -DPLATFORM_SUPPORT_D3D11=false -DPLATFORM_SUPPORT_D3D12=false -DSIMUL_BUILD_SAMPLES=false -DPLATFORM_BUILD_SAMPLES=false -DPLATFORM_BUILD_MD_LIBS=false -DTELEPORT_CLIENT_USE_D3D12=false -DTELEPORT_CLIENT_USE_VULKAN=true
    - name: Show CMake Output
      run: |
        dir ${{github.workspace}}/build_pc_client
        gc ${{github.workspace}}/build_pc_client/CMakeCache.txt
        gc ${{github.workspace}}/build_pc_client/firstparty/Platform/Vulkan/SimulVulkan_MT.vcxproj
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build_pc_client --config ${{env.WORKFLOW_BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build_pc_client
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.WORKFLOW_BUILD_TYPE}}

