name: Release

on:
  workflow_dispatch:
  label:
    types:
      - created

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 20
    env:
      WORKFLOW_BUILD_TYPE: Release
      WORKFLOW_VULKAN_DIR: D:/a/Teleport/Teleport/VULKAN_SDK
      VULKAN_SDK: D:/a/Teleport/Teleport/VULKAN_SDK
      VULKAN_SDK_DIR: D:/a/Teleport/Teleport/VULKAN_SDK

    steps:
    - name: Safe download workflow artifact
      uses: Legit-Labs/action-download-artifact@v2.18.0
      with:
        github_token: ${{secrets.TELEPORT_RELEASES_TOKEN}}
        workflow: Build PC Client
        branch: main
        name: installer
        path: ./installer
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        github-token: ${{secrets.TELEPORT_GENERIC_TOKEN}}
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: installer
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: installer
          
