name: Release

on:
  workflow_dispatch:
  label:
    types:
      - created

jobs:
  deploy:
    runs-on: windows-2022
    timeout-minutes: 20
    env:
      WORKFLOW_BUILD_TYPE: Release
      WORKFLOW_VULKAN_DIR: D:/a/Teleport/Teleport/VULKAN_SDK
      VULKAN_SDK: D:/a/Teleport/Teleport/VULKAN_SDK
      VULKAN_SDK_DIR: D:/a/Teleport/Teleport/VULKAN_SDK

    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{secrets.TELEPORT_GENERIC_TOKEN}}
        workflow: build_pc_client.yml
    - name: Show
      run: |
        ls -R .
          
